var p1 = document.getElementById("first");
var p2 = document.getElementsByClassName("special")[0];
var p3 = document.getElementsByTagName("p")[0];
var p4 = document.querySelector("#first");
var p5 = document.querySelector(".special");
var p6 = document.querySelectorAll(".special")[0];
var p7 = document.querySelector("p");
var p8 = document.querySelectorAll("p")[0];
var p9 = document.querySelector("h1 + p");